_wandb:
    value:
        cli_version: 0.27.0
        e:
            r54w1y956lzoe0fulqrw19j1q6yf11ky:
                args:
                    - --config
                    - configs/benchmark.yaml
                    - --wandb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1022870155264"
                        used: "311313580032"
                email: siddharthsrinivasan2002@gmail.com
                executable: C:\Users\sidsr\GPUs for Financial Engineering\.venv\Scripts\python.exe
                git:
                    commit: 7edd9ffdacb941521be32a13ae8a79910435843b
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-ef329102-4456-9943-0ff3-6d9a6f59c3b4
                host: Omen
                memory:
                    total: "16415322112"
                os: Windows-11-10.0.26200-SP0
                program: -m src.benchmarks.run_all
                python: CPython 3.12.10
                root: C:\Users\sidsr\GPUs for Financial Engineering
                startedAt: "2026-05-29T11:30:48.787155Z"
                writerId: r54w1y956lzoe0fulqrw19j1q6yf11ky
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.12.10
            "5": 0.27.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.27.0
            "13": windows-amd64
